{% set version = "0.1" %}
# Boost doesn't have ABI compat guarantees across versions,
# so fix the version throughout build and run time.
#{% set boost_version = "1.69" %}

package:
  name: parla_task
  version: {{ version }}

build:
  number: 17
  skip: true # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python=3.6
    - cython
    - galois=5
    - boost-cpp
    - cudatoolkit-dev
  run:
    - galois=5
    - python=3.6
    - numba
    #- psutil
    - cudatoolkit-dev

about:
  license: BSD
  summary: Low-level tasking runtime.

extra:
  recipe-maintainers:
    - insertinterestingnamehere
