{% set version = "4.0" %}
# Boost doesn't have ABI compat guarantees across versions,
# so fix the version throughout build and run time.
#{% set boost_version = "1.69" %}

package:
  name: galois
  version: {{ version }}

source:
  fn: Galois-release-{{version}}.zip
  url: https://github.com/IntelligentSoftwareSystems/Galois/archive/release-4.0.zip
  sha256: 5c41ae225b815f1f43f7c3ffb8b9d19b4c81375e3072156288dfc0d153643040
  patches:
    - remove_llvm_include.patch

build:
  number: 4
  skip: true # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - boost-cpp

about:
  home: iss.ices.utexas.edu/?p=projects/galois
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - insertinterestingnamehere
